baseURL = "https://example.com"

# This is a "landing page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "myTheme"

# The "title" of your website
title = "Landingpage for SMEs"

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Gerwald Gindra-Vady"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Landingpage with general info"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/background.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Gerwald - trust me: soon, I'm an engineer!"


    # Banner Section
    [params.HeroBanner]
        enable                = true
        background_image      = "images/background.jpg"
        title               = "HeroBanner"
        text               = "Some awesome subtext"
        button_text           = "Click me"

    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"